# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GDALOpen_cpp <- function(dsn, sds) {
    .Call(`_xrgdal_GDALOpen_cpp`, dsn, sds)
}

xrgdal_Warp <- function(xp, extent, dimension, projection) {
    .Call(`_xrgdal_xrgdal_Warp`, xp, extent, dimension, projection)
}

xrgdal_RasterIO <- function(xp, window) {
    .Call(`_xrgdal_xrgdal_RasterIO`, xp, window)
}

xrgdal_RasterSize <- function(xp) {
    .Call(`_xrgdal_xrgdal_RasterSize`, xp)
}

xrgdal_GDALClose <- function(xp) {
    .Call(`_xrgdal_xrgdal_GDALClose`, xp)
}

